name: pkgcheck

# This will cancel running jobs once a new run is triggered
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

on:
  # Manually trigger the Action under Actions/pkgcheck
  workflow_dispatch:
  # Run on every push to main
  push:
    branches:
      - main
      - master

jobs:
  pkgcheck:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
    - name: Check R version
      run: R --version
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.0'  # Specify the latest R version
    - name: Install dependencies
      run: |
        Rscript -e "install.packages(c('devtools', 'roxygen2'))"
        Rscript -e "devtools::install_deps(dependencies = TRUE)"
    - uses: ropensci-review-tools/pkgcheck-action@main
      with:
          summary-only: false
